name: burgerama
author: Daniel Stockhammer
description: Burgerama web UI written in Dart
homepage: https://github.com/dstockhammer/burgerama.web
dependencies:
  angular: ">=0.14.0"
  browser: any
  hammock: any
  google_maps: any
  less_node: any
transformers:
- angular
- less_node:
    entry_point: less\main.less
    output: web\style.css